export const baseStyles = {
  container: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    borderRadius: '8px',
    border: '1px solid var(--rfp-border, #e2e8f0)',
    backgroundColor: 'var(--rfp-bg, #ffffff)',
    color: 'var(--rfp-text, #1a202c)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    position: 'relative' as const,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 16px',
    borderBottom: '1px solid var(--rfp-border, #e2e8f0)',
    backgroundColor: 'var(--rfp-header-bg, #f7fafc)',
    fontSize: '13px',
    flexShrink: 0,
    gap: '12px',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    minWidth: 0,
    flex: 1,
  },
  fileName: {
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  fileSize: {
    color: 'var(--rfp-muted, #718096)',
    whiteSpace: 'nowrap' as const,
    fontSize: '12px',
  },
  body: {
    flex: 1,
    overflow: 'auto',
    position: 'relative' as const,
    minHeight: 0,
  },
  centerContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    padding: '20px',
  },
  error: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    padding: '40px 20px',
    color: 'var(--rfp-muted, #718096)',
    textAlign: 'center' as const,
  },
  errorIcon: {
    fontSize: '48px',
    opacity: 0.5,
  },
  loading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px',
    color: 'var(--rfp-muted, #718096)',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  toolbarButton: {
    background: 'none',
    border: '1px solid var(--rfp-border, #e2e8f0)',
    borderRadius: '4px',
    padding: '4px 8px',
    cursor: 'pointer',
    color: 'var(--rfp-text, #1a202c)',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
};
